# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50dd478530fbf0807d75d1e2ada3541f283707999aae8f85ec84afde1db2e0ca4674e2de807a4aa64ea8c93b21bd0a6940aff72593ac9f55a0c123c2daf676f0

test:
  secret_key_base: 99094fe03a03db8f847d565550a7137bcafe844b5f0847381a2b0ae8926775086b05b90b14b111869313cb804b9591682ab2dec44b6afb4dd14df151b9d1a930

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
